[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sais-pyobs"
version = "0.3.0"
description = "A high-performance OBS transfer tool for AI datasets."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
  {name = "huangjiajia", email = "1655979823@qq.com"}
]
urls = {Homepage = "https://github.com/huangpd/pyobs", Source = "https://github.com/huangpd/pyobs", Issues = "https://github.com/huangpd/pyobs/issues"}

dependencies = [
    "requests>=2.25.0",
    "huaweicloud-sdk-python-obs>=3.21.8",
    "tqdm"
]

[project.optional-dependencies]
dev = ["build", "twine"]

[tool.hatch.build.targets.wheel]
packages = ["src"]

# 自动发现 src 下的包
[tool.setuptools.packages.find]
where = ["src"]
